version: "3.8" #Docker Engine에 따른 Docker-compose version

services:
  mariadb:
    image: "mariadb:${tag}"
    container_name: "mariadb-${tag}"
    environment:
      - "MARIADB_DATABASE=${mariadb_database}"
      - "MARIADB_USER=${mariadb_user}"
      - "MARIADB_PASSWORD=${mariadb_password}"
      - "MARIADB_ROOT_PASSWORD=${mariadb_root_password}"
    ports:
      - "3306:3306"
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "29092:29092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:29092
    depends_on:
      - zookeeper
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
